const fs = require('fs')

const lines = []
lines.push("import { useState, useEffect } from 'react'")
lines.push("import { Search, TrendingUp, TrendingDown, User } from 'lucide-react'")
lines.push("import { supabase } from '../lib/supabase'")
lines.push("")
lines.push("interface Store {")
lines.push("  id: string")
lines.push("  town: string")
lines.push("  region: string")
lines.push("  manager_name: string")
lines.push("  phone: string")
lines.push("  wtd?: number")
lines.push("  trend?: string")
lines.push("  flagged?: number")
lines.push("  grades?: number")
lines.push("}")
lines.push("")
lines.push("const REGIONS = ['All','City','North','South','West']")
lines.push("")
lines.push("export default function Locations() {")
lines.push("  const [stores, setStores] = useState<Store[]>([])")
lines.push("  const [loading, setLoading] = useState(true)")
lines.push("  const [search, setSearch] = useState('')")
lines.push("  const [region, setRegion] = useState('All')")
lines.push("  const [selected, setSelected] = useState<string | null>(null)")
lines.push("")
lines.push("  useEffect(() => {")
lines.push("    supabase.from('stores').select('id, town, region, manager_name, phone').order('id')")
lines.push("      .then(({ data, error }) => {")
lines.push("        if (!error && data) {")
lines.push("          const enriched = data.map(s => ({")
lines.push("            ...s,")
lines.push("            wtd: Math.floor(Math.random() * 30) + 65,")
lines.push("            trend: Math.random() > 0.4 ? 'up' : 'down',")
lines.push("            flagged: Math.random() > 0.7 ? Math.floor(Math.random() * 3) : 0,")
lines.push("            grades: Math.floor(Math.random() * 50) + 30,")
lines.push("          }))")
lines.push("          setStores(enriched)")
lines.push("        }")
lines.push("        setLoading(false)")
lines.push("      })")
lines.push("  }, [])")
lines.push("")
lines.push("  const filtered = stores.filter(s => {")
lines.push("    const matchSearch = s.id.includes(search) || s.manager_name.toLowerCase().includes(search.toLowerCase()) || s.town.toLowerCase().includes(search.toLowerCase())")
lines.push("    const matchRegion = region === 'All' || s.region === region")
lines.push("    return matchSearch && matchRegion")
lines.push("  })")
lines.push("")
lines.push("  if (loading) return <div className=\"p-8 text-center text-gray-400\">Loading stores...</div>")
lines.push("")
lines.push("  return (")
lines.push("    <div className=\"p-4 space-y-4\">")
lines.push("      <div>")
lines.push("        <h1 className=\"text-xl font-bold text-gray-900\">Locations</h1>")
lines.push("        <p className=\"text-gray-500 text-xs mt-0.5\">{stores.length} stores in your franchise group</p>")
lines.push("      </div>")
lines.push("      <div className=\"grid grid-cols-4 gap-2\">")
lines.push("        {['City','North','South','West'].map(r => {")
lines.push("          const rs = stores.filter(s => s.region === r)")
lines.push("          const avg = rs.length ? (rs.reduce((a, s) => a + (s.wtd || 0), 0) / rs.length).toFixed(1) : '0'")
lines.push("          return (")
lines.push("            <div key={r} className=\"bg-white rounded-xl p-3 shadow-sm border border-gray-100 text-center\">")
lines.push("              <div className=\"text-xs text-gray-500 font-medium\">{r}</div>")
lines.push("              <div className={'text-lg font-bold mt-1 ' + (parseFloat(avg) >= 80 ? 'text-green-600' : 'text-yellow-600')}>{avg}%</div>")
lines.push("              <div className=\"text-xs text-gray-400\">{rs.length} stores</div>")
lines.push("            </div>")
lines.push("          )")
lines.push("        })}")
lines.push("      </div>")
lines.push("      <div className=\"relative\">")
lines.push("        <Search size={14} className=\"absolute left-3 top-1/2 -translate-y-1/2 text-gray-400\" />")
lines.push("        <input value={search} onChange={e => setSearch(e.target.value)}")
lines.push("          placeholder=\"Search store #, manager, town...\"")
lines.push("          className=\"w-full pl-8 pr-4 py-2.5 border border-gray-200 rounded-xl text-sm bg-white focus:outline-none focus:ring-2 focus:ring-[#CC0000]\" />")
lines.push("      </div>")
lines.push("      <div className=\"flex gap-2 flex-wrap\">")
lines.push("        {REGIONS.map(r => (")
lines.push("          <button key={r} onClick={() => setRegion(r)}")
lines.push("            className={'px-3 py-1.5 rounded-xl text-xs font-medium border transition ' + (region === r ? 'bg-[#CC0000] text-white border-[#CC0000]' : 'bg-white text-gray-600 border-gray-200')}>")
lines.push("            {r}")
lines.push("          </button>")
lines.push("        ))}")
lines.push("      </div>")
lines.push("      <div className=\"space-y-3\">")
lines.push("        {filtered.map(store => (")
lines.push("          <div key={store.id} onClick={() => setSelected(store.id === selected ? null : store.id)}")
lines.push("            className={'bg-white rounded-xl p-4 shadow-sm border-2 cursor-pointer transition ' + (selected === store.id ? 'border-[#CC0000]' : 'border-gray-100 hover:border-gray-300')}>")
lines.push("            <div className=\"flex items-center justify-between\">")
lines.push("              <div className=\"flex items-center gap-3\">")
lines.push("                <div className=\"w-11 h-11 bg-gray-100 rounded-xl flex items-center justify-center font-bold text-gray-700 text-xs text-center leading-tight\">#{store.id}</div>")
lines.push("                <div>")
lines.push("                  <div className=\"font-bold text-gray-900 text-sm\">#{store.id}</div>")
lines.push("                  <div className=\"text-xs text-gray-500 mt-0.5\">{store.town}</div>")
lines.push("                  <div className=\"text-xs text-gray-400 flex items-center gap-1 mt-0.5\"><User size={10} />{store.manager_name}</div>")
lines.push("                </div>")
lines.push("              </div>")
lines.push("              <div className=\"text-right\">")
lines.push("                <div className={'text-lg font-bold ' + ((store.wtd||0) >= 80 ? 'text-green-600' : (store.wtd||0) >= 70 ? 'text-yellow-600' : 'text-red-600')}>{store.wtd}%</div>")
lines.push("                <div className=\"flex items-center justify-end gap-1 text-xs mt-0.5\">")
lines.push("                  {store.trend === 'up'")
lines.push("                    ? <span className=\"text-green-600 flex items-center gap-0.5\"><TrendingUp size={11} />Up</span>")
lines.push("                    : <span className=\"text-red-500 flex items-center gap-0.5\"><TrendingDown size={11} />Down</span>")
lines.push("                  }")
lines.push("                  {(store.flagged||0) > 0 && <span className=\"ml-1 bg-red-100 text-red-600 px-1.5 py-0.5 rounded-full text-xs font-medium\">{store.flagged} flagged</span>}")
lines.push("                </div>")
lines.push("              </div>")
lines.push("            </div>")
lines.push("            {selected === store.id && (")
lines.push("              <div className=\"mt-4 pt-4 border-t border-gray-100 grid grid-cols-2 gap-3 text-sm\">")
lines.push("                <div><span className=\"text-gray-400 text-xs\">Region</span><div className=\"font-medium\">{store.region}</div></div>")
lines.push("                <div><span className=\"text-gray-400 text-xs\">Phone</span><div className=\"font-medium\">{store.phone}</div></div>")
lines.push("                <div><span className=\"text-gray-400 text-xs\">Grades This Week</span><div className=\"font-medium\">{store.grades}</div></div>")
lines.push("                <div><span className=\"text-gray-400 text-xs\">Flagged</span><div className={'font-medium ' + ((store.flagged||0) > 0 ? 'text-red-600' : 'text-green-600')}>{(store.flagged||0) > 0 ? store.flagged + ' issues' : 'None'}</div></div>")
lines.push("                <div className=\"col-span-2\">")
lines.push("                  <a href={'/kiosk/' + store.id} target=\"_blank\" className=\"block w-full text-center bg-[#CC0000] text-white text-xs font-semibold py-2 rounded-xl mt-1\">Open Kiosk View</a>")
lines.push("                </div>")
lines.push("              </div>")
lines.push("            )}")
lines.push("          </div>")
lines.push("        ))}")
lines.push("        {filtered.length === 0 && <div className=\"bg-white rounded-xl p-8 text-center text-gray-400 border border-gray-100\">No stores match your search</div>}")
lines.push("      </div>")
lines.push("    </div>")
lines.push("  )")
lines.push("}")

fs.writeFileSync('src/pages/Locations.tsx', lines.join('\n'), 'utf8')
console.log('wrote Locations.tsx')