const fs = require('fs')
let app = fs.readFileSync('src/App.tsx', 'utf8')
app = app.replace("\n        <Route path=\"/test\" element={<SupabaseTest />} />", "")
fs.writeFileSync('src/App.tsx', app)
console.log('done')