const fs = require('fs')
let login = fs.readFileSync('src/pages/Login.tsx', 'utf8')
login = login.replace('type="email" value={email} onChange={e => setEmail(e.target.value)}', 'type="text" value={email} onChange={e => setEmail(e.target.value)}')
fs.writeFileSync('src/pages/Login.tsx', login)
console.log('fixed Login.tsx')